### ISSUE TITLE
Question : Which Hardware / Water Flow Sensor can be used ?

### ISSUE THREAD

**Issue by Noschvie** [trlafleur/Flow-Sensor-Tasmota#3]
Please provide a list of water flow sensor devices to be used, thanks!

**Comment by trlafleur** [comment]
You can use almost any water flow sensor used in irrigation with this
code...

I've been using CTS ELF 1in flow sensors and the Dwyer Water Meter in my
systems. I have also tested with Badger and Rain-Bird sensors
The flow sensors that are K-Offset require a conditional circuit to shape
the pulse prior to the ESP32, schematic that I used is on web site. An
optical isolator could also be used. Pulse per unit of flow can be directly
connected to ESP32 with some minor protection, as they are a reed switch or
TTL output from an optical sensor.

https://www.creativesensortechnology.com/copy-of-pct-120
https://dwyer-inst.com/products/flow/water-meters.html

There are two basic types of water flow meters, some produce a pulse per
unit of flow,
and K-Offset flow meters.

Unit per flow meter, give a pulse per unit of flow, typical devices give 1
to 100 gal/pulse or
a pulse per cubic feet of water. One "unit" of water is 100 ccf or 748.052
gals.

Almost all of the turbine-type flow sensors used in irrigation, use two
calibration factors
specified: a “K”  and an “Offset”.

During calibration, the manufacturer measures the pulse rate outputs for a
number of precise flow rates.
These are plotted, but since the turbine has some friction, the graph will
not be
linear, especially at the low end and a linear regression is done to get a
best-fit straight line.
The “K” factor represents the slope of the fitted line and has a dimension
of pulses per unit volume moved.
The offset represents the small amount of liquid flow required to start the
turbine moving.
You can assume that if any pulses are arriving at all, at least the offset
volume of liquid is moving.

There does not seem to be a standard for how K-factor flow meters are
presented.
Flow sensors output a pulse stream at a frequency proportional to the flow
volume as calibrated,
with some sensors like CST, and RainBird, you multiply the pulse frequency
by the K factor to obtain a volume rate.
Others however like Badger, require you to divide the pulse frequency by K.

So there are two basic types of K-Offset flow sensors, CST and many others
are of type = 1,
Some like Badger are of type = 2. So read the vendor's datasheet!

~~ _/) ~~~~ _/) ~~~~ _/) ~~~~ _/) ~~

Tom Lafleur



On Tue, Jan 17, 2023 at 6:39 AM Norbert ***@***.***> wrote:
>
> Please provide a list of water flow sensor devices to be used, thanks!
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this thread.Message
ID: ***@***.***>
